from selenium.webdriver.common.by import By

class Order:
    TOP_ORDER_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g' and text()='Заказать']")
    BOTTOM_ORDER_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Заказать']")
    NAME_INPUT = (By.CSS_SELECTOR, "input[placeholder='* Имя']")
    SURNAME_INPUT = (By.CSS_SELECTOR, "input[placeholder='* Фамилия']")
    ADDRESS_INPUT = (By.CSS_SELECTOR, "input[placeholder='* Адрес: куда привезти заказ']")
    METRO_INPUT = (By.CSS_SELECTOR, "input[placeholder='* Станция метро']")
    DROPDOWN_METRO = (By.XPATH, "//div[@class='select-search__select']")
    TELEPHON_INPUT = (By.CSS_SELECTOR, "input[placeholder='* Телефон: на него позвонит курьер']")
    NEXT_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Далее']")
    
    DELIVERY_DATE = (By.CSS_SELECTOR, "input[placeholder='* Когда привезти самокат']")
    RENTAL_PERIOD = (By.XPATH, "//div[contains(@class, 'Dropdown-control')]")
    DROPDOWN_RENTAL_PERIOD = (By.XPATH, "//div[@class='Dropdown-placeholder is-selected']")
    RENTAL_PERIOD_DAY = (By.XPATH, "//div[text()='сутки']")
    RENTAL_PERIOD_TWO_DAYS = (By.XPATH, "//div[text()='двое суток']")
    RENTAL_PERIOD_THREE_DAYS = (By.XPATH, "//div[text()='трое суток']")
    RENTAL_PERIOD_FOUR_DAYS = (By.XPATH, "//div[text()='четверо суток']")
    RENTAL_PERIOD_FIVE_DAYS = (By.XPATH, "//div[text()='пятеро суток']")
    RENTAL_PERIOD_SIX_DAYS = (By.XPATH, "//div[text()='шестеро суток']")
    RENTAL_PERIOD_SEVEN_DAYS = (By.XPATH, "//div[text()='семеро суток']")
    COLOR_BLACK = (By.ID, "black")
    COLOR_GREY = (By.ID, "grey")
    COMMENT_INPUT = (By.CSS_SELECTOR, "input[placeholder='Комментарий для курьера']")
    FORMA_ORDER_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Заказать']")
    YES_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Да']")
    ORDER_DECORATED = (By.XPATH, "//div[contains(text(), 'Заказ оформлен')]")
    STATUS_BUTTON = (By.XPATH, "//button[@class='Button_Button__ra12g Button_Middle__1CSJM' and text()='Посмотреть статус']")
    SCOOTER_LOGO = (By.XPATH, "//img[@alt='Scooter']")
    YANDEX_LOGO = (By.XPATH, "//img[@alt='Yandex']")
    BODY = (By.TAG_NAME, 'body')